### PR TITLE
Add sastocansat model

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
Cansats are a educational platform for students studying satellites. Simulating cansats will enable students to iterate faster on software for development

**Describe your solution**
This PR adds a Software-In-The-Loop simulation target for PX4 SITL
To try it, run
```
make px4_sitl gazebo_cansat
```

**Test data / coverage**
Demo video can be found here:
[Demo](https://youtu.be/ZVbQqPUZ1FY)
Since PX4 is capable of logging the flight, the log can be visualized through flight review:
Log: https://review.px4.io/plot_app?log=35a0647d-f69f-4a19-bfe1-ea66d099a9a1

**Additional context**

### CODE REVIEW

**Comment by samanratna** [comment]
Hi there, I tried to make the build on my system. I got this message about missing the target. Can you help me with it ?
image

**Comment by Jaeyoung-Lim** [comment]
@Jaeyoung-Lim Are you sure you have the correct branch?

you need to be on `develop`

**Comment by samanratna** [comment]
Hi JaeyoungLim,

I followed the steps stated here
<https://dev.px4.io/master/en/setup/dev_env_windows_cygwin.html> and
performed the make px4_sitl gazebo_cansat.

-Saman

.

**Comment by Jaeyoung-Lim** [comment]
@SamanRatna Are you sure you cloned the firmware from this repository?

This is a thread for the pull request. If you have questions, please post it as an issue so that we can properly track them

**Comment by samanratna** [comment]
Yes JaeyoungLIm.

**Comment by samanratna** [comment]
hello there, I have this error here while running the make command. 
Do I need to have some configurations in my system to be able to work this out ?

image

**Comment by Jaeyoung-Lim** [comment]
@SamanRatna Can you share the full log on a new issue please?

**Comment by samanratna** [comment]
$ make px4_sitl gazebo_cansat
[367/528] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr/local
-- cmake build type: RelWithDebInfo
-- Using C++17 standard
CMake Error at /usr/share/cmake-3.14.5/Modules/FindBoost.cmake:2165 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:45 (find_package)


CMake Error at CMakeLists.txt:46 (find_package):
  By not providing "Findgazebo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gazebo", but
  CMake did not find one.

  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/cygdrive/c/PX4/home/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
[375/528] Building CXX object src/examples/work_item/CMakeFiles/examples__work_item.dir/WorkItemExample.cpp.o
FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-configure
cd /cygdrive/c/PX4/home/Firmware/build/px4_sitl_default/build_gazebo && /usr/bin/cmake.exe -DCMAKE_INSTALL_PREFIX=/usr/local -DSEND_ODOMETRY_DATA=ON -GNinja /cygdrive/c/PX4/home/Firmware/Tools/sitl_gazebo && /usr/bin/cmake.exe -E touch /cygdrive/c/PX4/home/Firmware/build/px4_sitl_default/external/Stamp/sitl_gazebo/sitl_gazebo-configure
[378/528] Building CXX object src/systemcmds/tests/CMakeFiles/systemcmds__tests.dir/test_matrix.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:226: px4_sitl] Error 1

**Comment by Jaeyoung-Lim** [comment]
@SamanRatna  Please move the discussion to a new issue

**Pull request merged**
